# Generated by Django 2.2.11 on 2020-03-07 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('user_email', models.EmailField(max_length=80, unique=True)),
                ('user_dob', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('user_mobile', models.CharField(max_length=10)),
            ],
        ),
    ]